/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class easyquiz_tcpsocket_TCPSocket */

#ifndef _Included_easyquiz_tcpsocket_TCPSocket
#define _Included_easyquiz_tcpsocket_TCPSocket
#ifdef __cplusplus
extern "C" {
#endif
#undef easyquiz_tcpsocket_TCPSocket_BUFFER_LENGTH
#define easyquiz_tcpsocket_TCPSocket_BUFFER_LENGTH 1024L
/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    winsockInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_winsockInit
  (JNIEnv *, jclass);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    socket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_socket
  (JNIEnv *, jclass);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    connect
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_connect
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    bind
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_bind
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    listen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_listen
  (JNIEnv *, jclass, jint);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    accept
 * Signature: (I)Leasyquiz/tcpsocket/TCPSocket;
 */
JNIEXPORT jobject JNICALL Java_easyquiz_tcpsocket_TCPSocket_accept
  (JNIEnv *, jclass, jint);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    send
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_send
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    receive
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_receive
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     easyquiz_tcpsocket_TCPSocket
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_easyquiz_tcpsocket_TCPSocket_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
