/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class easyquiz_thread_JThread */

#ifndef _Included_easyquiz_thread_JThread
#define _Included_easyquiz_thread_JThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     easyquiz_thread_JThread
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_easyquiz_thread_JThread_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
