/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyquiz.client;

import easyquiz.Question;
import easyquiz.TrueFalseQuestion;
import easyquiz.thread.JThread;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author aland
 */
public class CountdownPanel extends javax.swing.JPanel {
    private CountdownThread countdownThread;
    
    /**
     * Creates new form TrueFalseQuestion
     */
    public CountdownPanel() {
        initComponents();
    }

    public void countdown(long starting, long deadline, Question question) {
        this.countdownThread = new CountdownThread(starting, this.countdownLabel, () -> {
            MainFrame.getInstance().showQuestion(question, deadline);
        });
        
        this.countdownThread.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        countdownLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 232, 227));

        titleLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(25, 29, 99));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Next question in...");

        countdownLabel.setFont(new java.awt.Font("Segoe Print", 1, 72)); // NOI18N
        countdownLabel.setForeground(new java.awt.Color(0, 153, 0));
        countdownLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countdownLabel.setText("5");
        countdownLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(countdownLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countdownLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel countdownLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
