/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyquiz.client;

/**
 *
 * @author david
 */
public class CreateQuiz extends javax.swing.JPanel {

    /**
     * Creates new form CreateQuiz
     */
    public CreateQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        startPane = new javax.swing.JPanel();
        nameLabel2 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        startPane1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        joinBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        startPane.setBackground(new java.awt.Color(237, 232, 227));
        startPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        nameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel2.setText("Name:");
        startPane.add(nameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 88, -1));

        titleLabel.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Create Quiz");
        startPane.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 75));
        startPane.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 188, -1));

        startPane1.setBackground(new java.awt.Color(237, 232, 227));
        startPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        nameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel1.setText("Type:");
        startPane1.add(nameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 88, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "True or False", "3 Options", "4 Options" }));
        startPane1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 190, 20));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        startPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 440, 210));

        jScrollPane1.setViewportView(startPane1);

        startPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 500, 210));

        joinBtn.setBackground(new java.awt.Color(49, 205, 99));
        joinBtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        joinBtn.setForeground(new java.awt.Color(244, 243, 246));
        joinBtn.setText("Save");
        joinBtn.setToolTipText("");
        joinBtn.setFocusPainted(false);
        joinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinBtnActionPerformed(evt);
            }
        });
        startPane.add(joinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 80, 30));

        add(startPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void joinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinBtnActionPerformed
        /*
        Quiz q = new Quiz("Test Quiz");
        TopBar bar = new TopBar(nameField.getText(),"Test Quiz");
        //q.addQuestion(new TrueFalseQuestion("Is tabata a good person?",true));
        q.addQuestion(new Ans3Question("Is tabata a good person?","yes","of course", "absolutely", 3));
        this.remove(startPane);
        this.add(bar,BorderLayout.NORTH);
        if(q.getFirstQuestion() instanceof TrueFalseQuestion){
            this.add(new YesNoQuestionPane((TrueFalseQuestion)q.getFirstQuestion()),BorderLayout.CENTER);
        }else{
            this.add(new Ans3QuestionPane((Ans3Question)q.getFirstQuestion()),BorderLayout.CENTER);
        }
        this.revalidate();
        this.repaint();
        */
    }//GEN-LAST:event_joinBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JPanel startPane;
    private javax.swing.JPanel startPane1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
