/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyquiz.client;

import java.awt.Color;
import java.awt.Font;



/**
 *
 * @author aland
 */
public class HighScore extends javax.swing.JPanel {

    /**
     * Creates new form HighScore
     */
    public HighScore() {
        initComponents();
        highTable.getTableHeader().setForeground(new Color(25,29,99));
        highTable.getTableHeader().setFont(new Font("Segoe Print", Font.BOLD,12));
        highTable.getColumnModel().getColumn(0).setPreferredWidth(45);
        highTable.getColumnModel().getColumn(0).setMaxWidth(90);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        highLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        highTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(237, 232, 227));
        setLayout(new java.awt.BorderLayout());

        highLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        highLabel.setForeground(new java.awt.Color(25, 29, 99));
        highLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highLabel.setText("Highscore!");
        highLabel.setAlignmentX(0.5F);
        highLabel.setMaximumSize(new java.awt.Dimension(500, 150));
        highLabel.setPreferredSize(new java.awt.Dimension(500, 100));
        add(highLabel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N

        highTable.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        highTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Place", "User", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        highTable.setMaximumSize(new java.awt.Dimension(2147483647, 1200));
        highTable.setPreferredSize(new java.awt.Dimension(225, 800));
        highTable.setRowSelectionAllowed(false);
        highTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(highTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highLabel;
    private javax.swing.JTable highTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}