/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package easyquiz;

/**
 *
 * @author aland
 */
public class Ans3QuestionPane extends javax.swing.JPanel {

    /**
     * Creates new form Ans3Question
     */
    public Ans3QuestionPane(Ans3Question quest) {
        initComponents();
        questionLabel.setText(quest.getQuestion());
        opt1Button.setText(quest.getOp1());
        opt2Button.setText(quest.getOp2());
        opt3Button.setText(quest.getOp3());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLabel = new javax.swing.JLabel();
        opt1Button = new javax.swing.JButton();
        opt2Button = new javax.swing.JButton();
        opt3Button = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 232, 227));

        questionLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(25, 29, 99));
        questionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionLabel.setText("Your question goes here");

        opt1Button.setBackground(new java.awt.Color(244, 243, 246));
        opt1Button.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        opt1Button.setText("Continue");
        opt1Button.setFocusPainted(false);

        opt2Button.setBackground(new java.awt.Color(244, 243, 246));
        opt2Button.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        opt2Button.setText("Continue");
        opt2Button.setFocusPainted(false);

        opt3Button.setBackground(new java.awt.Color(244, 243, 246));
        opt3Button.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        opt3Button.setText("Continue");
        opt3Button.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opt2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opt3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 196, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(opt3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton opt1Button;
    private javax.swing.JButton opt2Button;
    private javax.swing.JButton opt3Button;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables
}
